name: IceAuth
main: eu.icecraft.iceauth.IceAuth
version: 1.1
author:  illusion9
description: Lightweight authorization plugin
commands:
    login:
        description: With this command a player can login!
        usage:
        aliases: l
    register:
        description: With this command a player can register!
        usage:
    changepassword:
        description: With this command you can change your password!
        usage:
    iceauth:
        description: Basic performance stats.
        usage:
    setfirstspawn:
        Description: Set where the player will spawn the first time he login.
        Usage: /setfirstspawn
    firstspawn:
        Description: Teleport the player to the first spawn.
        Usage: /firstspawn
    ref:
        Description: Get referral link
        Usage: /ref