name: IceAuth
main: eu.icecraft.iceauth.IceAuth
version: 1.0
author:  illusion9
description: Lightweight authorization plugin based on AuthMe
softdepends:
    - Spout
commands:
    login:
        description: With this command a player can login!
        usage:
        aliases: l
    register:
        description: With this command a player can register!
        usage:
    changepassword:
        description: With this command you can change your password!
        usage: